RESULT = pdt-test
SOURCES = \
  ../src/tfg.mli ../src/tfg.ml \
  ../src/program.mli ../src/program.ml \
  ulibs/utils.mli ulibs/utils.ml \
  ulibs/ustring.mli ulibs/ustring.ml \
  ulibs/utest.mli ulibs/utest.ml \
  src/testTFGgen.ml \
  src/maintest.ml
OCAMLMAKEFILE = ../OCamlMakefile
include $(OCAMLMAKEFILE)
